pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/Geetasundhar/order-management-system/tree/main/order_management'
            }
        }

        stage('Build Maven Project') {
            steps {
                bat 'mvn clean install'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t order-management-app .'
            }
        }

        stage('Run Docker Container') {
            steps {
                bat 'docker run -d -p 8082:8082 order-management-app'
            }
        }
    }
}